### ISSUE TITLE
Get artifact of solidity file in external GitHub repository

### ISSUE THREAD

**Issue by SKYBITDev3** [ItsNickBarry/hardhat-dependency-compiler#17]
I want the artifact of https://github.com/ZeframLou/create3-factory/blob/18cfad8d118b25a5092cdfed6bea9c932ca5b6eb/src/CREATE3Factory.sol to use in my hardhat scripts.

I tried 
```
yarn add -D https://github.com/ZeframLou/create3-factory/#18cfad8d118b25a5092cdfed6bea9c932ca5b6eb
```
which added `"create3-factory": "https://github.com/ZeframLou/create3-factory#18cfad8d118b25a5092cdfed6bea9c932ca5b6eb"` into dependencies in package.json, and the `create3-factory` directory was created with all the repository files under `node_modules` directory.

Then I added the path for `dependencyCompiler`:
```js
  dependencyCompiler: {
    paths: [
      "create3-factory/src/CREATE3Factory.sol",
    ],
  }
```
When I try to compile this error appears:
```
Error HH411: The library create3-factory, imported from contracts/hardhat-dependency-compiler/create3-factory/src/CREATE3Factory.sol, is not installed. Try installing it using npm.
```

What can be done?

**Comment by ItsNickBarry** [comment]
See this issue: https://github.com/NomicFoundation/hardhat/issues/1361

I think the same thing is happening in your case.  As a workaround, you could add a placeholder `package.json` to the dependency's directory in `node_modules`.  This could be done in an override of the `compile` task.

Closing because a fix would be out of scope of the plugin.  Comment if you have any questions.
